---
title: "Milestone 4"
author: "Grace Rotondo"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readxl)
library(janitor)
library(ggplot2)
library(fastDummies)
library(gt)
library(tidyverse)
```

```{r}
letterwinners <- read_excel("~/Library/Mobile Documents/com~apple~CloudDocs/Harvard/GOV1005 /Milestone_4/alum_data/WLAX_LETTERWINNER_DATA.xlsx")

alumnae <- read_excel("~/Library/Mobile Documents/com~apple~CloudDocs/Harvard/GOV1005 /Milestone_4/alum_data/FoHL_ALumnae_List_10.3.19.xls")
```

```{r}
#I cleaned letterwinners data and then filtered to exclude NA values in
#concentration column. I then mutated the concentration column with names of
#concentrations and the industry column with names of industries, so as to
#create a gt table, just for my own organization. I then selected concentration
#and industry to see the data next to each other. I'm still playing around with
#the data, but I think I want to plot the correlation between concentration and
#industry to see if there is any relationship between the variables.
letterwinners%>% 
  clean_names() %>% 
  #subset(select = -x6) %>% 
  #subset(select = -x11) %>% 
  filter(concentration != "NA",
         industry != "NA") %>% 
         #linked_in != "NA",
         #concentration != "NA",
         #secondary_concentration != "NA") %>% 

ggplot(aes(x = concentration)) + 
  geom_bar(aes(stat = "count", fill = industry))
  
  dummy <- data.frame(numbers = 1:3,
                    concentration  = c("Government", "Psychology", "Economics"),
                    stringsAsFactors = FALSE)
  
  #results <- fastDummies::dummy_cols(dummy)


  
  
  #filter(concentration == c("Government", 
                            #"Economics", 
                            #"Psychology"),
         #industry == c("Finance",
                       #"Medicine",
                       #"Consulting"))
  #group_by(concentration, industry)%>%  
 

letterwinners %>% 
  ggplot(aes(x = "concentration", fill = "industry")) +
    geom_bar()

```

"English", 
                            "Neurobiology",
                            "History of Art & Architecture",
                            "Sociology",
                            "Social Studies"
                            
                            "Retail, Consumer Goods",
                       "Nonprofit"

```{r}
#Possible GT
letterwinners %>% 
gt(rownames_to_stub = FALSE)
mutate(concentration = fct_relevel(concentration, c("Economics",
                               "Government",
                               "Biology",
                               "Neurobiology",
                               "Physics",
                               "Psychology",
                               "History of Art & Architecture",
                               "English",
                               "History"))) %>% 
  mutate(industry = fct_relevel(industry, c("Finance",
                               "Consulting",
                               "Medicine",
                               "Athletics Education",
                               "Education",
                               "Retail, Consumer Goods"))) %>% 
```

